[package]
description = "CLI tool to get the UTC datetime for a given natural language time/date description"
edition = "2021"
license = "ISC"
name = "tu"
version = "0.1.0"

[dependencies]
chrono = "0.4.35"
chrono-english = "0.1.7"
